import { color } from "framer-motion";
import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  tripsmobile,
  hotels,
  clothing,
  html,
  css,
  reactjs,
  iphones,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  docker,
  meta,
  starbucks,
  tesla,
  shopify,
  carrent,
  jobit,
  flutter,
  tripguide,
  bootstrap,
  threejs,
  pmgraves,
  quick,
  phones,
  cas,
  ipart,
  matebets,
  icepop,
  kasi_1,
  kasi_2,
  kasi_3,
  cv
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "projects",
    title: "Projects",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Front-End Developer",
    icon: web,
  },
  {
    title: "Backend Developer",
    icon: backend,
  },
  {
    title: "Mobile Developer",
    icon: mobile,
  },
  {
    title: "Graphic Designer",
    icon: creator,
  },
];

const technologies = [
  { name: "HTML 5", icon: html },
  { name: "CSS 3", icon: css },
  { name: "JavaScript", icon: javascript },
  { name: "React JS", icon: reactjs },
  { name: "Tailwind CSS", icon: tailwind },
  { name: "Bootstrap", icon: bootstrap },
  { name: "Three JS", icon: threejs },
  { name: "flutter", icon: flutter },
  { name: "python", icon: git },
  { name: "figma", icon: figma },
];

const projects = [
  {
    id: "pm-grave-closures",
    name: "PM Grave Closures",
    description: "Soweto based Grave Closure business that specializes in the maintenance of graves.",
    longDescription: "PM Grave Closures is a professional web presence built for a Soweto-based burial services business. The site was designed to convey trust and professionalism while being fully responsive for mobile visitors. It includes a clear service listing, contact section, and gallery of past work.",
    goal: "Build a credible, professional website for a local business with no digital presence — enabling them to reach new customers online.",
    techStack: ["HTML", "CSS", "JavaScript"],
    tags: [{ name: "html #css #javascript", color: "blue-text-gradient" }],
    image: pmgraves,
    link: "https://pmgraveclosures.netlify.app/",
    year: "2023",
    category: "Web",
  },
  {
    id: "trip-tips",
    name: "Trip Tips",
    description: "Travel blog with ideas and insights on cool places to visit all around the world.",
    longDescription: "Trip Tips is a fully responsive travel blog built with React. Users can browse destination cards and travel advice curated from around the world. The app features a clean Bootstrap-powered layout and component-driven architecture for easy content scalability.",
    goal: "Create an engaging travel blog platform that demonstrates component-based UI design and responsive web development skills.",
    techStack: ["React", "Bootstrap", "CSS"],
    tags: [{ name: "react #bootstrap", color: "blue-text-gradient" }],
    image: tripsmobile,
    link: "http://Kamva-pro.github.io/Trip-tips",
    year: "2025",
    category: "Web",
  },
  {
    id: "mate-bets",
    name: "Mate Bets",
    description: "An interactive chess betting website.",
    longDescription: "Mate Bets is a full-stack chess betting platform. Users can create accounts, participate in chess betting rooms, and track their betting history in real-time. Built with React on the frontend and Express.js backed by Supabase — including real-time updates via Firebase and secure API communication via Axios.",
    goal: "Build a full-stack real-time betting platform demonstrating skills in authentication, database management, WebSocket events, and complex React state management.",
    techStack: ["React", "Express.js", "Axios", "Supabase", "Firebase"],
    tags: [{ name: "react #express.js #axios #supabase #firebase", color: "blue-text-gradient" }],
    image: matebets,
    link: "https://mate-bets-qif33hn3nq-bq.a.run.app/",
    year: "2024",
    category: "Full-Stack",
  },
  {
    id: "kasi-in",
    name: "Kasi IN",
    description: "A kasi food delivery service app.",
    longDescription: "Kasi IN is a mobile food delivery app built for township communities. It enables users to browse local restaurants, place orders, and track delivery status in real time. The app was built with React Native and Expo for cross-platform support, backed by a Node.js REST API, PostgreSQL database, and Supabase for authentication.",
    goal: "Create an accessible food delivery experience tailored for township communities — leveraging mobile-first development with real-time order tracking.",
    techStack: ["React Native", "Expo", "Node.js", "PostgreSQL", "Supabase", "Firebase"],
    tags: [{ name: "react-native #expo #node.js #postgreSQL #supabase #firebase", color: "blue-text-gradient" }],
    image: kasi_3,
    link: "https://github.com/Kamva-pro/Kasi-IN.git",
    year: "2024",
    category: "Mobile",
  },
  {
    id: "cas",
    name: "Central Air Solutions",
    description: "Corporate website for an Industrial Air & Compressor Specialist company.",
    longDescription: "Central Air Solutions (CAS) PTY LTD is a proudly 100% black-owned company specializing in industrial and agricultural sectors. Built with React, Vite, Tailwind CSS, and Framer Motion, the site features a modern, animated interface to showcase their engineering-driven excellence and 24/7 technical support services.",
    goal: "Create a professional, high-performance web presence that reflects the company's commitment to quality, safety, and innovation in the industrial sector.",
    techStack: ["React", "Vite", "Tailwind CSS", "Framer Motion"],
    tags: [{ name: "react #vite #tailwindcss #framermotion", color: "blue-text-gradient" }],
    image: cas,
    link: "https://casgroup.co.za",
    year: "2026",
    category: "Web",
  },
  {
    id: "educonnect",
    name: "EduConnect",
    description: "A communication platform bridging the gap between schools and parents.",
    longDescription: "EduConnect is a dedicated platform designed to streamline communication between educational institutions and parents. It provides a centralized hub for announcements, academic progress tracking, and direct messaging, ensuring parents remain engaged and informed about their children's school life.",
    goal: "Facilitate seamless, instantaneous communication between schools and parents, fostering a collaborative educational environment.",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    tags: [{ name: "react #nodejs #mongodb #express", color: "blue-text-gradient" }],
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    link: "https://educonnect.africa",
    year: "2026",
    category: "Full-Stack",
  },
];

export { services, technologies, projects };
